global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # FastAPI application metrics
  - job_name: 'fastapi-agent'
    static_configs:
      - targets: ['fastapi-app:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Ollama service monitoring (if it exposes metrics)
  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    # Ollama might not expose Prometheus metrics by default
    # This is for future compatibility
    
  # System metrics with node_exporter (can be added later)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']